spring:
  datasource:
    url: jdbc:postgresql://${PETS_DB_SERVER}/petsdev
    username: test
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults=false: false
    database-platform: org.hibernate.dialect.PostgreSQL11Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

  jackson:
    default-property-inclusion: NON_NULL