version: '3.5'
services:

  users-postgres:
    image: postgres:11
    volumes:
      - ./data/users-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=usersdev
    networks:
      - users

  pets-postgres:
    image: postgres:11
    volumes:
      - ./data/animals-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=petsdev
    networks:
      - pets

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 9099:8080
    volumes:
      - gradle-cache:/root/.gradle
    env_file:
      - ./gateway/.env
    networks:
      - main

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports: # Can be removed because of the gateway, only enabled for swagger access
      - 9090:8080
    volumes:
      - ./gradle:/root/.gradle
    env_file:
      - ./user-service/.env
    depends_on:
      - users-postgres
    networks:
      - users
      - main

  pet-service:
    build:
      context: ./pet-service
      dockerfile: Dockerfile
    ports: # Can be removed because of the gateway, only enabled for swagger access
      - 9091:8080
    volumes:
      - ./gradle:/root/.gradle
    env_file:
      - ./pet-service/.env
    depends_on:
      - pets-postgres
    networks:
      - pets
      - main

volumes:
  gradle-cache:

networks:
  main:
    driver: bridge
  users:
    driver: bridge
  pets:
    driver: bridge

